name: ts-package-starter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: install project dependencies
      run: yarn --prefer-offline

    - name: test
      run: yarn test

    - name: build
      run: yarn build
